apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec:
  selector:
    app: goserver
  type: NodePort
  ports:
    - name: goserver-service
      targetPort: 8080
      port: 80
      protocol: TCP
      nodePort: 30001
